addons:
  apt:
    packages:
    - nodejs
language: python
sudo: false
python:
- 3.5
- 3.8
env:
- TOX_ENV=django22
- TOX_ENV=csslint
- TOX_ENV=eslint
- TOX_ENV=pycodestyle
- TOX_ENV=pylint
before_install:
- export BOTO_CONFIG=/dev/null
- pip install pip==20.0.2
cache:
  directories:
  - $HOME/.cache/pip
install:
- make requirements_travis
- pip install coveralls
script:
- tox -e $TOX_ENV
branches:
  only:
  - master
after_success: coveralls
